### ISSUE TITLE
Some project codes are inconsistent with the ones in PHP SALSAH

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/ark-resolver-data#12]
Moved from https://github.com/dhlab-basel/ark-resolver/issues/13 following discussion in https://github.com/dhlab-basel/ark-resolver/issues/11.

**Comment by benjamingeer** [comment]
@lrosenth sent me these IDs exported from PHP SALSAH:

|Project ID|Name|Decimal ID in PHP SALSAH|
|------|---|---|
|0803|incunabula|3|
|0806|webern|6|
|0808|dokubib|8|
|080C|kuhaba|12|
|080E|LIMC|14|
|0811|postcards|17|
|0812|SGV|18|
|0813|Bruno Manser Fonds|19|
|0814|wackernagel|20|
|0816|vitrails|22|
|0817|Parzival|23|
|0818|bosnienfoto|24|
|081B|delille|27|
|081C|HdM|28|
|081F|litfeuilleton|31|

There are some conflicts between these project IDs and the ones in this repository. Also, in the Knora test data, dokubib is `0804`.

**Comment by irinaschubert** [comment]
I checked the shortcodes and IDs and the inconsistencies seem to be resolved now. I hereby close this issue.
