### ISSUE TITLE
Update of the DaSCH entry on the NAAN Registry

### ISSUE THREAD

**Issue by julsraemy** [dasch-swiss/ark-resolver-data#29]
On the [Name Assigning Authority Number (NAAN) Registry](https://n2t.net/e/pub/naan_registry.txt) or by clicking on http://n2t.net/ark:/72163/, DaSCH is still listed with http://dasch.swiss as its redirect URL (`where`). For this reason, redirection of any ARKs minted by the DaSCH from the Name-To-Thing (N2T) doesn't work and always redirect to a 404 page on the DaSCH website.

For instance:

`ark:/72163/0812-179488a1f0d91-0.2021422` when using http://n2t.net/ark:/72163/0812-179488a1f0d91-0.2021422 do not redirect to https://data.dasch.swiss/resources/422236

To fix this, I've asked through this [form](https://n2t.net/e/naan_request) to update the NAAN registry and put the following URL: http://ark.dasch.swiss

**Comment by irinaschubert** [comment]
Hi @julsraemy , thank you for your effort! The correct URL is now registered: http://n2t.net/ark:/72163/ 

You can try it out with: http://n2t.net/ark:/72163/1/082B/SQkTPdHdTzq_gqbwj6QR=AR
This is redirected to http://ark.dasch.swiss/ark:/72163/1/082B/SQkTPdHdTzq_gqbwj6QR=AR
Which is then redirected to: https://admin.dasch.swiss/resource/http:%2F%2Frdfh.ch%2F082B%2FSQkTPdHdTzq_gqbwj6QR-A

The ARK you used above is somehow invalid (where did you get it from?). But it is redirected to the ARK resolver correctly.

I hereby close this issue.
